export enum configuration {
    APPLICATION_NAME='APPLICATION_NAME',
    PORT='PORT',
    DATABASE_URI='DATABASE_URI',
    TOKEN_SECRET='TOKEN_SECRET',
    SMTP_TRANSPORT='SMTP_TRANSPORT',
    ENV_URL='ENV_URL',
    AWS_S3_BUCKET='AWS_S3_BUCKET',
    AWS_ACCESS_KEY_ID='AWS_ACCESS_KEY_ID',
    AWS_ACCESS_SECRET_KEY='AWS_ACCESS_SECRET_KEY',
}