export enum configuration {
    APPLICATION_NAME='APPLICATION_NAME',
    PORT='PORT',
    DATABASE_URI='DATABASE_URI',
    TOKEN_SECRET='TOKEN_SECRET',
    SMTP_TRANSPORT='SMTP_TRANSPORT',
    ENV_URL='ENV_URL'
}